name: docker

on: 
  push:
    branches: [main]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create image tag
        run: echo "TAG=v1.0.${GITHUB_RUN_ID}" >> ${GITHUB_ENV}
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/packer:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/packer:${{ env.TAG }}
